# Generated by Django 5.2.3 on 2025-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ExpenseCost',
            field=models.DecimalField(decimal_places=2, max_digits=75),
        ),
    ]
